site_name: Sheffield Young Carers
site_slogan: a voluntary organisation working with and on behalf of young carers aged 8-21 across Sheffield
site_url: http://www.sheffieldyoungcarers.org.uk
webthumb_key: ff1e5c1f36807f9e87868f9c01c33dbb
latest_stories_items_per_page: 6
development:
  site_name: Sheffield Young Carers
  recaptcha_public_key: 6LcDGOkSAAAAAEwTYa0f4cXjJhnNkcNKjDGzctWK
  recaptcha_private_key: 6LcDGOkSAAAAACuX7p0dOJshBszAGo5-iE9vfzbS
production:
  recaptcha_public_key: 6LeQFukSAAAAAPHdC_aA33gQxuz76ePJKjk-8FPP
  recaptcha_private_key: 6LeQFukSAAAAAEdpGQx17SUjiI_oQHSJkE2AE5U6
