site_name: Sheffield Young Carers
site_slogan: a voluntary organisation working with and on behalf of young carers aged 8-21 across Sheffield
site_url: demo.sheffieldyoungcarers.org.uk
webthumb_key: ff1e5c1f36807f9e87868f9c01c33dbb
latest_stories_items_per_page: 6
development:
  site_name: Sheffield Young Carers