photo_resize_geometry: 500x500>
site_name: Tramlines Version 6
site_slogan: Knowledge is power and power is fun.
site_email: info@yoomee.com
site_url: 77.86.30.132:3333
development:
  site_name: Tramlines Version 6 Development
  site_url: www.ianslocalhost.com:3333